export const dsPaginationSafelist = [
  'flex',
  'flex-wrap',
  'items-center',
  'justify-end',
  'gap-3',
  'min-w-[100px]',
  'gap-1',
  'h-8',
  'min-w-8',
  'px-2',
  'rounded-md',
  'text-sm',
  'font-600',
  'transition-colors',
  'duration-150',
  'focus:outline-none',
  'focus-visible:ring-2',
  'focus-visible:ring-[var(--ring)]',
  'bg-[var(--primary)]',
  'text-[var(--primary-fg)]',
  'text-[var(--muted-fg)]',
  'hover:bg-[var(--muted)]',
  'hover:text-[var(--fg)]',
] as const