/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DsButton: typeof import('@feugene/granularity/components/DsButton')['DsButton']
    DsInput: typeof import('@feugene/granularity/components/DsInput')['DsInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vHotkey: typeof import('@feugene/granularity/directives/hotkey')['vHotkey']
  }
}
