export const dsDataTableSafelist = [
  'font-700',
  'text-xs',
  'px-4',
  'py-3',
  'text-left',
  'text-right',
  'inline-flex',
  'items-center',
  'gap-2',
  'text-[var(--muted-fg)]',
  'hover:text-[var(--fg)]',
  'transition-colors',
  'focus:outline-none',
  'focus-visible:ring-2',
  'focus-visible:ring-[var(--ring)]',
  'rounded',
  'h-4',
  'w-4',
  'border-t',
  'border-[var(--brd)]',
] as const