import { splitClassTokens } from '../shared/classTokens'
import {
  transferActionIconClass,
  transferActionInertClass,
  transferActionsClass,
  transferActionsSizes,
  transferCounterClass,
  transferGhostClass,
  transferGhostCountClass,
  transferGhostLabelClass,
  transferEmptyClass,
  transferEmptySizes,
  transferHeaderBase,
  transferHeaderSizes,
  transferIndicatorAfterClass,
  transferIndicatorBeforeClass,
  transferLabelClass,
  transferListBase,
  transferMarkBase,
  transferMarkIconClass,
  transferMarkSizes,
  transferMarkStates,
  transferDragCursorClass,
  transferOptionBase,
  transferOptionGrabClass,
  transferOptionPlainClass,
  transferOptionSizes,
  transferOptionStates,
  transferPanelBase,
  transferPanelDropClass,
  transferReorderBase,
  transferReorderIconClass,
  transferReorderSizes,
  transferRootBase,
  transferSearchBase,
  transferSearchSizes,
  transferStatusClass,
  transferTitleClass,
} from './grTransferStyles'

// `gr-transfer-vacated` и `gr-transfer-arrived` сюда не входят: это обычные
// классы из `<style>` компонента, а не утилиты — генерировать их нечем.
export const grTransferSafelist = [...new Set([
  ...Object.values(transferHeaderSizes).flatMap(splitClassTokens),
  ...Object.values(transferOptionSizes).flatMap(splitClassTokens),
  ...Object.values(transferMarkSizes).flatMap(splitClassTokens),
  ...Object.values(transferSearchSizes).flatMap(splitClassTokens),
  ...Object.values(transferEmptySizes).flatMap(splitClassTokens),
  ...Object.values(transferActionsSizes).flatMap(splitClassTokens),
  ...Object.values(transferReorderSizes).flatMap(splitClassTokens),
  ...Object.values(transferOptionStates).flatMap(splitClassTokens),
  ...Object.values(transferMarkStates).flatMap(splitClassTokens),
  ...splitClassTokens(transferRootBase),
  ...splitClassTokens(transferPanelBase),
  ...splitClassTokens(transferPanelDropClass),
  ...splitClassTokens(transferHeaderBase),
  ...splitClassTokens(transferTitleClass),
  ...splitClassTokens(transferCounterClass),
  ...splitClassTokens(transferGhostClass),
  ...splitClassTokens(transferGhostLabelClass),
  ...splitClassTokens(transferGhostCountClass),
  ...splitClassTokens(transferSearchBase),
  ...splitClassTokens(transferListBase),
  ...splitClassTokens(transferOptionBase),
  ...splitClassTokens(transferOptionGrabClass),
  ...splitClassTokens(transferOptionPlainClass),
  // Курсор жеста: ставится условием в шаблоне и в `grTransferOptionClass`.
  ...splitClassTokens(transferDragCursorClass),
  ...splitClassTokens(transferMarkBase),
  ...splitClassTokens(transferMarkIconClass),
  ...splitClassTokens(transferLabelClass),
  ...splitClassTokens(transferIndicatorBeforeClass),
  ...splitClassTokens(transferIndicatorAfterClass),
  ...splitClassTokens(transferEmptyClass),
  ...splitClassTokens(transferActionsClass),
  ...splitClassTokens(transferActionIconClass),
  ...splitClassTokens(transferActionInertClass),
  ...splitClassTokens(transferReorderBase),
  ...splitClassTokens(transferReorderIconClass),
  ...splitClassTokens(transferStatusClass),
])]
