/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GrButton: typeof import('@feugene/granularity/components/GrButton')['GrButton']
    GrCalendar: typeof import('@feugene/granularity-chrono/components/GrCalendar')['GrCalendar']
    GrDatePicker: typeof import('@feugene/granularity-chrono/components/GrDatePicker')['GrDatePicker']
    GrFormField: typeof import('@feugene/granularity/components/GrFormField')['GrFormField']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
