/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GrBadge: typeof import('@feugene/granularity/components/GrBadge')['GrBadge']
    GrButton: typeof import('@feugene/granularity/components/GrButton')['GrButton']
    GrCalendar: typeof import('@feugene/granularity-chrono/components/GrCalendar')['GrCalendar']
    GrCard: typeof import('@feugene/granularity/components/GrCard')['GrCard']
    GrChartLine: typeof import('@feugene/granularity-charts/components/GrChartLine')['GrChartLine']
    GrDatePicker: typeof import('@feugene/granularity-chrono/components/GrDatePicker')['GrDatePicker']
    GrDateRangePicker: typeof import('@feugene/granularity-chrono/components/GrDateRangePicker')['GrDateRangePicker']
    GrDateTimePicker: typeof import('@feugene/granularity-chrono/components/GrDateTimePicker')['GrDateTimePicker']
    GrDialog: typeof import('@feugene/granularity/components/GrDialog')['GrDialog']
    GrFormField: typeof import('@feugene/granularity/components/GrFormField')['GrFormField']
    GrRelativeTime: typeof import('@feugene/granularity-chrono/components/GrRelativeTime')['GrRelativeTime']
    GrSegmented: typeof import('@feugene/granularity/components/GrSegmented')['GrSegmented']
    GrSparkline: typeof import('@feugene/granularity-charts/components/GrSparkline')['GrSparkline']
    GrSwitch: typeof import('@feugene/granularity/components/GrSwitch')['GrSwitch']
    GrTable: typeof import('@feugene/granularity/components/GrTable')['GrTable']
    GrTimePicker: typeof import('@feugene/granularity-chrono/components/GrTimePicker')['GrTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
