/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GrBadge: typeof import('@feugene/granularity/components/GrBadge')['GrBadge']
    GrButton: typeof import('@feugene/granularity/components/GrButton')['GrButton']
    GrCalendar: typeof import('@feugene/granularity-chrono/components/GrCalendar')['GrCalendar']
    GrCameraCapture: typeof import('@feugene/granularity-media/components/GrCameraCapture')['GrCameraCapture']
    GrChartArea: typeof import('@feugene/granularity-charts/components/GrChartArea')['GrChartArea']
    GrChartBar: typeof import('@feugene/granularity-charts/components/GrChartBar')['GrChartBar']
    GrChartBullet: typeof import('@feugene/granularity-charts/components/GrChartBullet')['GrChartBullet']
    GrChartFunnel: typeof import('@feugene/granularity-charts/components/GrChartFunnel')['GrChartFunnel']
    GrChartHeatmap: typeof import('@feugene/granularity-charts/components/GrChartHeatmap')['GrChartHeatmap']
    GrChartLine: typeof import('@feugene/granularity-charts/components/GrChartLine')['GrChartLine']
    GrChartPie: typeof import('@feugene/granularity-charts/components/GrChartPie')['GrChartPie']
    GrChartRadar: typeof import('@feugene/granularity-charts/components/GrChartRadar')['GrChartRadar']
    GrChartWaterfall: typeof import('@feugene/granularity-charts/components/GrChartWaterfall')['GrChartWaterfall']
    GrCheckbox: typeof import('@feugene/granularity/components/GrCheckbox')['GrCheckbox']
    GrChip: typeof import('@feugene/granularity/components/GrChip')['GrChip']
    GrDashboard: typeof import('@feugene/granularity-dashboard/components/GrDashboard')['GrDashboard']
    GrDashboardItem: typeof import('@feugene/granularity-dashboard/components/GrDashboardItem')['GrDashboardItem']
    GrDashboardItemSettings: typeof import('@feugene/granularity-dashboard/components/GrDashboardItemSettings')['GrDashboardItemSettings']
    GrDashboardPalette: typeof import('@feugene/granularity-dashboard/components/GrDashboardPalette')['GrDashboardPalette']
    GrDashboardToolbar: typeof import('@feugene/granularity-dashboard/components/GrDashboardToolbar')['GrDashboardToolbar']
    GrDataTable: typeof import('@feugene/granularity/components/GrDataTable')['GrDataTable']
    GrDatePicker: typeof import('@feugene/granularity-chrono/components/GrDatePicker')['GrDatePicker']
    GrDateRangePicker: typeof import('@feugene/granularity-chrono/components/GrDateRangePicker')['GrDateRangePicker']
    GrDateTimePicker: typeof import('@feugene/granularity-chrono/components/GrDateTimePicker')['GrDateTimePicker']
    GrDialog: typeof import('@feugene/granularity/components/GrDialog')['GrDialog']
    GrDuration: typeof import('@feugene/granularity-chrono/components/GrDuration')['GrDuration']
    GrFormField: typeof import('@feugene/granularity/components/GrFormField')['GrFormField']
    GrImageCrop: typeof import('@feugene/granularity-media/components/GrImageCrop')['GrImageCrop']
    GrInput: typeof import('@feugene/granularity/components/GrInput')['GrInput']
    GrLink: typeof import('@feugene/granularity/components/GrLink')['GrLink']
    GrPagination: typeof import('@feugene/granularity/components/GrPagination')['GrPagination']
    GrRadioGroup: typeof import('@feugene/granularity/components/GrRadioGroup')['GrRadioGroup']
    GrRelativeTime: typeof import('@feugene/granularity-chrono/components/GrRelativeTime')['GrRelativeTime']
    GrRichText: typeof import('@feugene/granularity-editor/components/GrRichText')['GrRichText']
    GrSegmented: typeof import('@feugene/granularity/components/GrSegmented')['GrSegmented']
    GrSelect: typeof import('@feugene/granularity/components/GrSelect')['GrSelect']
    GrSparkline: typeof import('@feugene/granularity-charts/components/GrSparkline')['GrSparkline']
    GrSwitch: typeof import('@feugene/granularity/components/GrSwitch')['GrSwitch']
    GrTimePicker: typeof import('@feugene/granularity-chrono/components/GrTimePicker')['GrTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
