export const dsEmptyStateSafelist = [
  'rounded-[var(--ds-radius-lg)]',
  'border',
  'border-[var(--brd)]',
  'bg-[var(--card)]',
  'p-6',
  'text-center',
  'flex',
  'justify-center',
  'h-12',
  'w-12',
  'rounded-[12px]',
  'bg-[var(--muted)]',
  'items-center',
  'h-6',
  'w-6',
  'text-[var(--muted-fg)]',
  'mt-4',
  'text-[14px]',
  'font-700',
  'mt-1',
  'text-[13px]',
] as const