import { splitClassTokens } from '../../internal/classTokens'
import { dashboardFrameSafelist } from '../GrDashboardFrame/frameSafelist'
import {
  actionsClass,
  bodyClass,
  bodySizes,
  cardBodyClass,
  cardClass,
  draggingClass,
  headerClass,
  headerSizes,
  overflowClass,
  overlayHeaderClass,
  overlayHeaderHiddenClass,
  overlayHeaderVisibleClass,
  overlaySpacerClass,
  paddingSizes,
  rootClass,
  titleClass,
} from './grDashboardItemStyles'

export const grDashboardItemSafelist = [...new Set([
  ...dashboardFrameSafelist,
  ...Object.values(headerSizes).flatMap(splitClassTokens),
  ...Object.values(bodySizes).flatMap(splitClassTokens),
  ...Object.values(paddingSizes).flatMap(splitClassTokens),
  ...Object.values(overflowClass).flatMap(splitClassTokens),
  ...splitClassTokens(rootClass),
  ...splitClassTokens(draggingClass),
  ...splitClassTokens(headerClass),
  ...splitClassTokens(titleClass),
  ...splitClassTokens(bodyClass),
  ...splitClassTokens(cardClass),
  ...splitClassTokens(cardBodyClass),
  ...splitClassTokens(actionsClass),
  ...splitClassTokens(overlayHeaderClass),
  ...splitClassTokens(overlayHeaderHiddenClass),
  ...splitClassTokens(overlayHeaderVisibleClass),
  ...splitClassTokens(overlaySpacerClass),
])]
