import { splitClassTokens } from '../shared/classTokens'
import { grButtonSafelist } from '../GrButton/safelist'
import {
  grRadioButtonDisabledCheckedClass,
  grRadioButtonDisabledClass,
  grRadioControlCheckedClass,
  grRadioControlDisabledClass,
  grRadioControlInvalidClass,
  grRadioControlUncheckedClass,
  grRadioControlSizes,
  grRadioDescriptionSizes,
  grRadioDotBaseClass,
  grRadioDotSizes,
  grRadioDotCheckedClass,
  grRadioDotDisabledClass,
  grRadioDotUncheckedClass,
  grRadioEnabledClass,
  grRadioLabelCheckedColorClass,
  grRadioLabelColorClass,
  grRadioLabelSizes,
  grRadioRootDisabledClass,
  grRadioRootReadonlyClass,
  grRadioRootEnabledClass,
} from './grRadioStyles'

export const grRadioSafelist = [...new Set([
  ...grButtonSafelist,
  ...splitClassTokens(grRadioEnabledClass),
  ...splitClassTokens(grRadioButtonDisabledClass),
  ...splitClassTokens(grRadioButtonDisabledCheckedClass),
  ...splitClassTokens(grRadioRootDisabledClass),
  ...splitClassTokens(grRadioRootEnabledClass),
  ...splitClassTokens(grRadioRootReadonlyClass),
  ...splitClassTokens(grRadioControlCheckedClass),
  ...splitClassTokens(grRadioControlUncheckedClass),
  ...splitClassTokens(grRadioControlDisabledClass),
  ...splitClassTokens(grRadioControlInvalidClass),
  ...splitClassTokens(grRadioDotCheckedClass),
  ...splitClassTokens(grRadioDotUncheckedClass),
  ...splitClassTokens(grRadioDotDisabledClass),
  ...splitClassTokens(grRadioDotBaseClass),
  ...Object.values(grRadioControlSizes).flatMap(splitClassTokens),
  ...Object.values(grRadioDotSizes).flatMap(splitClassTokens),
  ...Object.values(grRadioLabelSizes).flatMap(splitClassTokens),
  ...Object.values(grRadioDescriptionSizes).flatMap(splitClassTokens),
  ...splitClassTokens(grRadioLabelColorClass),
  ...splitClassTokens(grRadioLabelCheckedColorClass),
])]
