import { splitClassTokens } from '../shared/classTokens'
import { grButtonSafelist } from '../GrButton/safelist'
import {
  grRadioButtonDisabledCheckedClass,
  grRadioButtonDisabledClass,
  grRadioControlCheckedClass,
  grRadioControlDisabledClass,
  grRadioControlInvalidClass,
  grRadioControlUncheckedClass,
  grRadioDescriptionClass,
  grRadioDotBaseClass,
  grRadioDotCheckedClass,
  grRadioDotDisabledClass,
  grRadioDotUncheckedClass,
  grRadioEnabledClass,
  grRadioLabelCheckedClass,
  grRadioLabelClass,
  grRadioRootDisabledClass,
  grRadioRootEnabledClass,
} from './grRadioStyles'

export const grRadioSafelist = [...new Set([
  ...grButtonSafelist,
  ...splitClassTokens(grRadioEnabledClass),
  ...splitClassTokens(grRadioButtonDisabledClass),
  ...splitClassTokens(grRadioButtonDisabledCheckedClass),
  ...splitClassTokens(grRadioRootDisabledClass),
  ...splitClassTokens(grRadioRootEnabledClass),
  ...splitClassTokens(grRadioControlCheckedClass),
  ...splitClassTokens(grRadioControlUncheckedClass),
  ...splitClassTokens(grRadioControlDisabledClass),
  ...splitClassTokens(grRadioControlInvalidClass),
  ...splitClassTokens(grRadioDotCheckedClass),
  ...splitClassTokens(grRadioDotUncheckedClass),
  ...splitClassTokens(grRadioDotDisabledClass),
  ...splitClassTokens(grRadioDotBaseClass),
  ...splitClassTokens(grRadioLabelClass),
  ...splitClassTokens(grRadioLabelCheckedClass),
  ...splitClassTokens(grRadioDescriptionClass),
])]
