import { splitClassTokens } from '../shared/classTokens'
import {
  cellPaddings,
  columnDraggingClass,
  columnDropAfterClass,
  columnDropBeforeClass,
  columnHandleActiveClass,
  columnHandleClass,
  columnPinnedClass,
  columnPinnedLeftEdgeClass,
  columnPinnedRightEdgeClass,
  columnResizerClass,
  columnResizerHoverClass,
  columnResizerLineActiveClass,
  columnResizerLineClass,
  headerGaps,
  headerTextSizes,
  placeholderPaddings,
  rowSelectedClass,
  selectColumnWidths,
  spinnerSizes,
} from './grDataTableStyles'

export const grDataTableSafelist = [...new Set([
  ...Object.values(cellPaddings).flatMap(splitClassTokens),
  ...Object.values(placeholderPaddings).flatMap(splitClassTokens),
  ...Object.values(headerTextSizes).flatMap(splitClassTokens),
  ...Object.values(selectColumnWidths).flatMap(splitClassTokens),
  ...Object.values(headerGaps).flatMap(splitClassTokens),
  ...Object.values(spinnerSizes).flatMap(splitClassTokens),
  ...splitClassTokens(columnHandleClass),
  ...splitClassTokens(columnHandleActiveClass),
  ...splitClassTokens(columnDraggingClass),
  ...splitClassTokens(columnDropBeforeClass),
  ...splitClassTokens(columnDropAfterClass),
  ...splitClassTokens(columnResizerClass),
  ...splitClassTokens(columnResizerLineClass),
  ...splitClassTokens(columnResizerLineActiveClass),
  ...splitClassTokens(columnResizerHoverClass),
  ...splitClassTokens(columnPinnedClass),
  ...splitClassTokens(columnPinnedLeftEdgeClass),
  ...splitClassTokens(columnPinnedRightEdgeClass),
  ...splitClassTokens(rowSelectedClass),
])]
