import { splitClassTokens } from '../shared/classTokens'
import {
  contentBase,
  groupCollapsedClass,
  groupLabelClass,
  headerBase,
  itemActiveClass,
  itemBadgeClass,
  itemBase,
  itemChevronClass,
  itemChevronExpandedClass,
  itemChildrenClass,
  itemCollapsedClass,
  itemDisabledClass,
  itemExpandedClass,
  itemIdleClass,
  itemLetterClass,
  itemNestClass,
  rootBase,
  rootPositions,
  subtitleClass,
  titleClass,
} from './grSidebarStyles'

export const grSidebarSafelist = [...new Set([
  ...splitClassTokens(rootBase),
  ...Object.values(rootPositions).flatMap(splitClassTokens),
  ...splitClassTokens(headerBase),
  ...splitClassTokens(titleClass),
  ...splitClassTokens(subtitleClass),
  ...splitClassTokens(contentBase),
  ...splitClassTokens(itemBase),
  ...splitClassTokens(itemCollapsedClass),
  ...splitClassTokens(itemExpandedClass),
  ...splitClassTokens(itemDisabledClass),
  ...splitClassTokens(itemActiveClass),
  ...splitClassTokens(itemIdleClass),
  ...splitClassTokens(itemLetterClass),
  ...splitClassTokens(itemBadgeClass),
  ...splitClassTokens(itemNestClass),
  ...splitClassTokens(itemChildrenClass),
  ...splitClassTokens(itemChevronClass),
  ...splitClassTokens(itemChevronExpandedClass),
  ...splitClassTokens(groupLabelClass),
  ...splitClassTokens(groupCollapsedClass),
])]
