import { createReadyExamples } from './shared'
import type { PackageDocOverride } from './types'

export const composablePackageDocOverrides: Record<string, PackageDocOverride> = {
  useTheme: {
    overview: [
      '`useTheme` хранит текущую тему приложения, переключает CSS-state на `document.documentElement` и умеет работать как с persistence, так и без неё.',
      '`initThemeEarly` стоит использовать до монтирования Vue, чтобы избежать мигания темы при первом рендере.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-theme-runtime',
        title: 'Runtime toggle with non-persistent mode',
        description: 'Demo переключает тему в рантайме и показывает сценарий `persist: false`, подходящий для embedded flows.',
        previewKey: 'use-theme-runtime',
        code: [
          "import { initThemeEarly, useTheme } from '@feugene/granularity'",
          '',
          'initThemeEarly({ storageKey: "app-theme", persist: true })',
          '',
          'const theme = useTheme({ persist: false, storageKey: "feature-preview-theme" })',
          'theme.toggleTheme()',
        ].join('\n'),
        note: '`persist: false` не читает и не пишет `localStorage`, но всё равно применяет CSS-theme к корневому элементу.',
      },
    ]),
    apiSections: [
      {
        key: 'parameters',
        title: 'Parameters',
        origin: 'manual',
        items: [
          { name: 'storageKey', type: 'string', description: 'Ключ в `localStorage`, по умолчанию `fint-ds-theme`.' },
          { name: 'persist', type: 'boolean', description: 'Если `false`, composable не работает с `localStorage` и подходит для SSR/embedded сценариев.' },
        ],
      },
      {
        key: 'returns',
        title: 'Returns',
        origin: 'manual',
        items: [
          { name: 'theme', type: "Ref<'light' | 'dark'>", description: 'Текущее значение темы.' },
          { name: 'isDark', type: 'ComputedRef<boolean>', description: 'Derived-flag для условного UI.' },
          { name: 'setTheme(next)', type: '(next: ThemeName) => void', description: 'Явно устанавливает тему и, при необходимости, пишет её в storage.' },
          { name: 'toggleTheme()', type: '() => void', description: 'Переключает тему между `light` и `dark`.' },
          { name: 'initTheme()', type: '() => void', description: 'Применяет текущее значение темы к DOM-дереву.' },
          { name: 'initThemeEarly(options)', type: '(options?: UseThemeOptions) => void', description: 'Bootstrap-helper для раннего применения темы до mount приложения.' },
        ],
      },
    ],
    usage: [
      'Вызывайте `initThemeEarly()` в entrypoint до `createApp(...).mount(...)`, если важно избежать flicker.',
      'В feature/demo контекстах можно использовать `persist: false`, чтобы не загрязнять глобальный storage продукта.',
    ],
    caveats: [
      'Composable пишет тему в `document.documentElement.dataset.theme` и `theme-dark` class, поэтому app-shell стили должны опираться на эти маркеры.',
      'Несколько независимых вызовов `useTheme` влияют на один и тот же DOM-root; если нужна строгая изоляция, нужен отдельный host/document.',
    ],
    integrationNotes: [
      'Используйте как app-shell primitive для theme switcher, settings page и embedded preview flows.',
      'Сценарии persistence и раннего init удобнее описывать прямо в bootstrap-коде, а не только внутри компонентов.',
    ],
  },
  useToast: {
    overview: [
      '`useToast` управляет shared reactive очередью toast-уведомлений и отдаёт единый API для push/dismiss/clear из любого consumer-а приложения.',
      'Для отображения очереди нужен mounted toast host, например `GrToaster` в app-shell showcase.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-toast-queue',
        title: 'Shared toast queue with sticky notifications',
        description: 'Demo показывает `push`, `dismiss`, `clear` и sticky toast через `timeoutMs = 0`.',
        previewKey: 'use-toast-queue',
        code: [
          "import { useToast } from '@feugene/granularity'",
          '',
          'const toast = useToast()',
          'const id = toast.push({',
          '  title: "Saved",',
          '  message: "Profile updated",',
          '  tone: "success",',
          '  timeoutMs: 0,',
          '})',
          'toast.dismiss(id)',
          'toast.clear()',
        ].join('\n'),
        note: 'Возвращаемый `id` нужен для ручного dismiss конкретного уведомления.',
      },
    ]),
    apiSections: [
      {
        key: 'parameters',
        title: 'Toast input',
        origin: 'manual',
        items: [
          { name: 'title', type: 'string', description: 'Обязательный заголовок toast.' },
          { name: 'message', type: 'string', description: 'Дополнительный текст уведомления.' },
          { name: 'variant', type: "'info' | 'success' | 'warning' | 'danger'", description: 'Визуальный вариант toast, по умолчанию `info`.' },
          { name: 'timeoutMs', type: 'number', description: 'Автоматическое закрытие; `0` делает уведомление sticky.' },
        ],
      },
      {
        key: 'returns',
        title: 'Returns',
        origin: 'manual',
        items: [
          { name: 'list', type: 'ComputedRef<Toast[]>', description: 'Shared reactive список уведомлений для всех consumers.' },
          { name: 'push(input)', type: '(input: ToastInput) => string', description: 'Добавляет toast в начало очереди и возвращает `id`.' },
          { name: 'dismiss(id)', type: '(id: string) => void', description: 'Удаляет конкретный toast из очереди.' },
          { name: 'clear()', type: '() => void', description: 'Очищает всю очередь уведомлений.' },
        ],
      },
    ],
    usage: [
      'Добавьте toast host (`GrToaster` или аналогичный shell-компонент) один раз в корень приложения.',
      'Используйте returned `id`, если toast должен закрываться вручную после завершения пользовательского действия.',
    ],
    caveats: [
      '`useToast` использует общий reactive store, поэтому изменения видны всем consumers внутри приложения.',
      'Без host-компонента уведомления будут попадать в очередь, но пользователь их не увидит.',
    ],
    integrationNotes: [
      'Подходит для app-shell notifications, optimistic actions и feature-level feedback сообщений.',
      'В showcase-shell уже должен быть mounted toaster host, поэтому demo отражает production-like интеграцию.',
    ],
  },
  useDialogService: {
    overview: [
      '`useDialogService` — императивный сервис диалогов в духе `ElMessageBox` из Element Plus: `confirm`, `prompt` и `alert` вызываются прямо из `<script>`/`.ts`, без вставки компонента в шаблон.',
      'Хост монтируется лениво в `document.body` и наследует app-контекст (i18n, тему, `granular-provider`); диалоги сериализуются FIFO-очередью, поэтому не накладываются друг на друга.',
      'Под капотом сервис переиспользует декларативные `GrConfirmDialog`/`GrPromptDialog`, а серверные ошибки в async-`onConfirm` рендерит через `GrResponseErrorBanner`.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-dialog-service-confirm',
        title: 'Imperative confirm (destructive, sm)',
        description: 'Compact destructive confirm с `size: "sm"`, semantic `confirmTone: "danger"` и кастомными `confirmText`/`cancelText`. Возвращает `Promise<boolean>`.',
        previewKey: 'use-dialog-service-confirm',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function removeWorkspace() {',
          "  const ok = await dialog.confirm('This action cannot be undone.', {",
          "    title: 'Delete workspace?',",
          "    size: 'sm',",
          "    confirmText: 'Delete',",
          "    cancelText: 'Keep',",
          "    confirmTone: 'danger',",
          '  })',
          '  if (ok) {',
          '    // ... perform deletion',
          '  }',
          '}',
        ].join('\n'),
        note: '`confirm` резолвится `true` по Confirm и `false` по Cancel/Esc/backdrop — без reject.',
      },
      {
        id: 'use-dialog-service-prompt',
        title: 'Imperative prompt (required, md)',
        description: 'Запрос строки с `label`, `placeholder`, `required` и `size: "md"`. Возвращает `Promise<string | null>` (`null` — отмена).',
        previewKey: 'use-dialog-service-prompt',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function renameProject() {',
          "  const name = await dialog.prompt('Pick a new project name.', {",
          "    title: 'Rename project',",
          "    size: 'md',",
          "    label: 'Project name',",
          "    placeholder: 'e.g. Atlas',",
          '    required: true,',
          "    confirmText: 'Save',",
          '  })',
          '  if (name !== null) {',
          '    // ... persist the new name',
          '  }',
          '}',
        ].join('\n'),
        note: 'Пустое значение блокирует Confirm, пока `required` не удовлетворён; отмена резолвит `null`.',
      },
      {
        id: 'use-dialog-service-alert',
        title: 'Imperative alert (single button, lg)',
        description: 'Информационный диалог с одной кнопкой подтверждения, `size: "lg"` и кастомным `confirmText`. Возвращает `Promise<void>`.',
        previewKey: 'use-dialog-service-alert',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function notifySaved() {',
          "  await dialog.alert('Your workspace settings have been saved.', {",
          "    title: 'Saved',",
          "    size: 'lg',",
          "    confirmText: 'Got it',",
          '  })',
          '  // ... continue after acknowledgement',
          '}',
        ].join('\n'),
        note: '`alert` не показывает кнопку Cancel и резолвится `void` после подтверждения/закрытия.',
      },
      {
        id: 'use-dialog-service-network',
        title: 'Async onConfirm (network errors + validation)',
        description: 'Imperative `prompt` с async-`onConfirm`, который имитирует сетевой запрос: кнопка Confirm уходит в loading, серверная валидация (HTTP 422) раскладывается на баннер и поле через `ctx.setRawError`, а обрыв сети (`throw`) распознаётся как `kind: "network"`. Диалог остаётся открытым до успешной отправки.',
        previewKey: 'use-dialog-service-network',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          'let attempt = 0',
          '',
          'async function inviteTeammate() {',
          "  const email = await dialog.prompt('Send an invite to a teammate.', {",
          "    title: 'Invite teammate',",
          "    label: 'Work email',",
          "    placeholder: 'name@company.com',",
          '    required: true,',
          "    confirmText: 'Send invite',",
          '    // Подключаем Laravel-пресет поверх ядра: fieldErrors лягут на поле `value`.',
          '    errorParsers: presets => [...presets.core, presets.laravel],',
          '    async onConfirm(ctx) {',
          '      attempt += 1',
          '      // Имитируем сетевой запрос — Confirm автоматически переходит в loading.',
          '      await new Promise(resolve => setTimeout(resolve, 700))',
          '',
          '      if (attempt === 1) {',
          '        // Серверная валидация (HTTP 422): баннер + ошибка под полем ввода.',
          '        await ctx.setRawError(',
          "          new Response(JSON.stringify({",
          "            message: 'The given data was invalid.',",
          "            errors: { value: ['This email is already invited.'] },",
          '          }), {',
          '            status: 422,',
          "            headers: { 'Content-Type': 'application/json' },",
          '          }),',
          '        )',
          '        return false',
          '      }',
          '',
          '      if (attempt === 2) {',
          '        // Обрыв сети: throw автоматически прогоняется через парсеры → kind: "network".',
          "        throw new TypeError('Failed to fetch')",
          '      }',
          '',
          '      // Успех на третьей попытке: диалог закрывается, prompt резолвится значением.',
          '    },',
          '  })',
          '  if (email !== null) {',
          '    // ... persist invitation',
          '  }',
          '}',
        ].join('\n'),
        note: 'Возврат `false` или `throw`/reject оставляет диалог открытым с показанной ошибкой; `setRawError` сам различает валидацию (422 → warning + поле) и сетевой сбой (network → danger-баннер).',
      },
    ]),
    apiSections: [
      {
        key: 'returns',
        title: 'Service methods',
        origin: 'manual',
        items: [
          { name: 'confirm(message, options?)', type: 'DialogPromise<boolean>', description: 'Диалог подтверждения; резолвится `true`/`false`.' },
          { name: 'prompt(message, options?)', type: 'DialogPromise<string | null>', description: 'Запрос строки; `null` — отмена/закрытие.' },
          { name: 'alert(message, options?)', type: 'DialogPromise<void>', description: 'Информационный диалог с одной кнопкой.' },
          { name: 'open(kind, message, options?)', type: 'DialogPromise<DialogResult>', description: 'Низкоуровневый вызов с дискриминируемым `{ action, value }`.' },
          { name: 'closeAll()', type: '() => void', description: 'Закрыть все активные и ожидающие в очереди диалоги.' },
          { name: 'setAppContext(ctx)', type: '(ctx: AppContext | null) => void', description: 'Явно задать app-контекст для вызовов вне `setup`.' },
        ],
      },
      {
        key: 'parameters',
        title: 'Common options',
        origin: 'manual',
        items: [
          { name: 'title', type: 'string', description: 'Заголовок диалога.' },
          { name: 'size', type: 'GrDialogSize', description: 'Размер диалога (`sm` / `md` / `lg` / ...).' },
          { name: 'confirmText / cancelText', type: 'string', description: 'Подписи кнопок Confirm и Cancel.' },
          { name: 'confirmTone / confirmVariant', type: 'GrButtonTone / GrButtonVariant', description: 'Семантика и вариант кнопки подтверждения.' },
          { name: 'onConfirm', type: '(ctx) => void | boolean | Promise<...>', description: 'Async-обработчик с loading и обработкой ошибок сервера.' },
          { name: 'errorParsers', type: 'ResponseErrorParser[] | (presets) => ...', description: 'Стратегия парсинга серверных ошибок; по умолчанию universal core.' },
        ],
      },
    ],
    usage: [
      'Используйте для одноразовых сценариев «спросить и забыть» прямо из обработчиков и сторов, без декларативного компонента в шаблоне.',
      'Передавайте `onConfirm` для async-операций: кнопка Confirm переходит в loading, а ошибки сервера показываются прямо в диалоге.',
    ],
    caveats: [
      'Методы работают только в браузере; вызовы вне `setup` требуют предварительного `setAppContext(...)`, иначе i18n/тема могут не наследоваться.',
      'Диалоги сериализуются очередью FIFO: следующий показывается только после закрытия предыдущего.',
    ],
    integrationNotes: [
      'Сервис — тонкий оркестратор поверх `GrConfirmDialog`/`GrPromptDialog`; декларативные компоненты остаются для встроенных в страницу сценариев.',
      'Для серверной валидации используйте `ctx.setRawError(...)` — ошибка раскладывается на баннер `GrResponseErrorBanner` и поля формы.',
    ],
  },
}