import { createReadyExamples } from './shared'
import type { PackageDocOverride } from './types'

export const composablePackageDocOverrides: Record<string, PackageDocOverride> = {
  useAnnouncer: {
    overview: [
      '`useAnnouncer` — общий живой регион (`aria-live`) пакета: один канал объявлений на документ, из которого приложение говорит скринридеру то, что произошло, но не отрисовалось.',
      'Граница простая: состояние виджета («загружается», «осталось 12 символов») остаётся своим регионом внутри виджета, а событие («скопировано», «строка удалена») уходит объявителю — своего места в разметке у него нет.',
      'Композабл не требует setup-контекста: его зовут из стора, обработчика или перехватчика запросов. Внутри пакета на нём уже работают `GrInputTag` и `GrImageViewer`.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-announcer-polite',
        title: 'Polite: событие без отражения в UI',
        description: 'Копирование в буфер — классический случай: визуально не меняется ничего, и без объявления для незрячего пользователя нажатие выглядит как «ничего не произошло».',
        previewKey: 'use-announcer-polite',
        code: [
          "import { useAnnouncer } from '@feugene/granularity'",
          '',
          'const { announce } = useAnnouncer()',
          '',
          'async function copyLink(url: string) {',
          '  await navigator.clipboard.writeText(url)',
          "  announce('Ссылка скопирована')",
          '}',
        ].join('\n'),
        note: 'По умолчанию `polite`: диктор дочитает начатое и только потом скажет сообщение.',
      },
      {
        id: 'use-announcer-assertive',
        title: 'Assertive: то, что нельзя пропустить',
        description: '`assertive` прерывает текущую речь. Уместен для отказа операции и потери соединения — и только для них: поток ассертивных объявлений делает страницу неработающей.',
        previewKey: 'use-announcer-assertive',
        code: [
          "import { useAnnouncer } from '@feugene/granularity'",
          '',
          'const { announce } = useAnnouncer()',
          '',
          'function onSaveFailed(reason: string) {',
          '  announce(`Не удалось сохранить: ${reason}`, { politeness: \'assertive\' })',
          '}',
        ].join('\n'),
        note: 'Ассертивный регион — `role="alert"`; полайтный — `role="status"`. Оба стоят в документе заранее и пусты до первого сообщения.',
      },
      {
        id: 'use-announcer-results',
        title: 'Результат фильтрации с автоочисткой',
        description: 'Число найденного меняется от ввода к вводу, поэтому объявление живёт недолго: `clearAfterMs` стирает текст, чтобы пользователь виртуального курсора не наткнулся на устаревшее число при обходе страницы.',
        previewKey: 'use-announcer-results',
        code: [
          "import { useAnnouncer } from '@feugene/granularity'",
          '',
          'const { announce } = useAnnouncer()',
          '',
          'function onFiltered(count: number) {',
          '  announce(`Найдено ${count}`, { clearAfterMs: 4000 })',
          '}',
        ].join('\n'),
        note: '`clearAfterMs: 0` оставляет текст навсегда — так стоит делать только с тем, что остаётся правдой.',
      },
    ]),
    apiSections: [
      {
        key: 'parameters',
        title: 'announce(message, options)',
        origin: 'manual',
        items: [
          { name: 'message', type: 'string', description: 'Текст объявления. Пустая строка игнорируется.' },
          { name: 'politeness', type: "'polite' | 'assertive'", description: 'Куда писать: `status`-регион (по умолчанию) или `alert`-регион, прерывающий речь.' },
          { name: 'clearAfterMs', type: 'number', description: 'Через сколько мс стереть текст. По умолчанию `7000`; `0` — не стирать.' },
        ],
      },
      {
        key: 'returns',
        title: 'Returns',
        origin: 'manual',
        items: [
          { name: 'announce(message, options?)', type: '(message: string, options?: GrAnnounceOptions) => void', description: 'Объявляет сообщение выбранным регионом.' },
          { name: 'clear(politeness?)', type: "(politeness?: 'polite' | 'assertive') => void", description: 'Стирает текст региона; без аргумента — обоих.' },
        ],
      },
    ],
    usage: [
      'Зовите `useAnnouncer()` в `setup`, если можете: регион встанет в документ заранее, а часть AT не объявляет регион, который появляется сразу с текстом.',
      'Для события, у которого нет места в разметке, — объявитель. Для состояния, которое виджет и так рендерит, — свой регион рядом с содержимым.',
      '`assertive` — только для отказа операции и потери соединения.',
    ],
    caveats: [
      'Регион один на документ, а не на приложение: это сток в единственный канал AT страницы, и два региона не изолируют приложения, а рискуют объявить одно и то же дважды. Плагина у объявителя поэтому нет.',
      'На сервере `announce()` — no-op: живой регион это узел документа, переносить между запросами нечего. Ни `ClientOnly`, ни клиентской проверки не нужно.',
      'Хост помечен `data-gr-live-region` и не гасится `inert` при открытии модалки — иначе объявитель молчал бы ровно там, где «сохранено» и «ошибка сети» и нужны.',
    ],
    integrationNotes: [
      'Внутри пакета на объявителе уже работают `GrInputTag` (добавление, удаление, предел набора) и `GrImageViewer` (смена кадра из-под собственного `inert`).',
      'Восемь остальных живых регионов пакета остаются на местах намеренно: они рендерят состояние своего виджета, а не транзитивное событие.',
    ],
  },
  useTheme: {
    overview: [
      '`useTheme` хранит текущую тему приложения, переключает CSS-state на `document.documentElement` и умеет работать как с persistence, так и без неё.',
      '`initThemeEarly` стоит использовать до монтирования Vue, чтобы избежать мигания темы при первом рендере.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-theme-runtime',
        title: 'Runtime toggle with non-persistent mode',
        description: 'Demo переключает тему в рантайме и показывает сценарий `persist: false`, подходящий для embedded flows.',
        previewKey: 'use-theme-runtime',
        code: [
          "import { initThemeEarly, useTheme } from '@feugene/granularity'",
          '',
          'initThemeEarly({ storageKey: "app-theme", persist: true })',
          '',
          'const theme = useTheme({ persist: false, storageKey: "feature-preview-theme" })',
          'theme.toggleTheme()',
        ].join('\n'),
        note: '`persist: false` не читает и не пишет `localStorage`, но всё равно применяет CSS-theme к корневому элементу.',
      },
    ]),
    apiSections: [
      {
        key: 'parameters',
        title: 'Parameters',
        origin: 'manual',
        items: [
          { name: 'storageKey', type: 'string', description: 'Ключ в `localStorage`, по умолчанию `gr-theme`.' },
          { name: 'persist', type: 'boolean', description: 'Если `false`, composable не работает с `localStorage` и подходит для SSR/embedded сценариев.' },
        ],
      },
      {
        key: 'returns',
        title: 'Returns',
        origin: 'manual',
        items: [
          { name: 'theme', type: "Ref<'light' | 'dark'>", description: 'Текущее значение темы.' },
          { name: 'isDark', type: 'ComputedRef<boolean>', description: 'Derived-flag для условного UI.' },
          { name: 'setTheme(next)', type: '(next: ThemeName) => void', description: 'Явно устанавливает тему и, при необходимости, пишет её в storage.' },
          { name: 'toggleTheme()', type: '() => void', description: 'Переключает тему между `light` и `dark`.' },
          { name: 'initTheme()', type: '() => void', description: 'Применяет текущее значение темы к DOM-дереву.' },
          { name: 'initThemeEarly(options)', type: '(options?: UseThemeOptions) => void', description: 'Bootstrap-helper для раннего применения темы до mount приложения.' },
        ],
      },
    ],
    usage: [
      'Вызывайте `initThemeEarly()` в entrypoint до `createApp(...).mount(...)`, если важно избежать flicker.',
      'В feature/demo контекстах можно использовать `persist: false`, чтобы не загрязнять глобальный storage продукта.',
    ],
    caveats: [
      'Composable пишет тему в `document.documentElement.dataset.theme`, поэтому app-shell стили должны опираться на этот маркер.',
      'Несколько независимых вызовов `useTheme` влияют на один и тот же DOM-root; если нужна строгая изоляция, нужен отдельный host/document.',
      'В SSR `setTheme`/`toggleTheme` требуют `app.use(granularityThemePlugin)`: без него состояние модульное, то есть общее на все запросы. Чтение `theme`/`isDark` на сервере работает и без плагина.',
    ],
    integrationNotes: [
      'Используйте как app-shell primitive для theme switcher, settings page и embedded preview flows.',
      'Сценарии persistence и раннего init удобнее описывать прямо в bootstrap-коде, а не только внутри компонентов.',
    ],
  },
  useToast: {
    overview: [
      '`useToast` управляет shared reactive очередью toast-уведомлений и отдаёт единый API для push/dismiss/clear из любого consumer-а приложения.',
      'Для отображения очереди нужен mounted toast host, например `GrToaster` в app-shell showcase.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-toast-queue',
        title: 'Shared toast queue with sticky notifications',
        description: 'Demo показывает `push`, `dismiss`, `clear` и sticky toast через `timeoutMs = 0`.',
        previewKey: 'use-toast-queue',
        code: [
          "import { useToast } from '@feugene/granularity'",
          '',
          'const toast = useToast()',
          'const id = toast.push({',
          '  title: "Saved",',
          '  message: "Profile updated",',
          '  tone: "success",',
          '  timeoutMs: 0,',
          '})',
          'toast.dismiss(id)',
          'toast.clear()',
        ].join('\n'),
        note: 'Возвращаемый `id` нужен для ручного dismiss конкретного уведомления.',
      },
    ]),
    apiSections: [
      {
        key: 'parameters',
        title: 'Toast input',
        origin: 'manual',
        items: [
          { name: 'title', type: 'string', description: 'Обязательный заголовок toast.' },
          { name: 'message', type: 'string', description: 'Дополнительный текст уведомления.' },
          { name: 'variant', type: "'info' | 'success' | 'warning' | 'danger'", description: 'Визуальный вариант toast, по умолчанию `info`.' },
          { name: 'timeoutMs', type: 'number', description: 'Автоматическое закрытие; `0` делает уведомление sticky.' },
        ],
      },
      {
        key: 'returns',
        title: 'Returns',
        origin: 'manual',
        items: [
          { name: 'list', type: 'ComputedRef<Toast[]>', description: 'Shared reactive список уведомлений для всех consumers.' },
          { name: 'push(input)', type: '(input: ToastInput) => string', description: 'Добавляет toast в начало очереди и возвращает `id`.' },
          { name: 'dismiss(id)', type: '(id: string) => void', description: 'Удаляет конкретный toast из очереди.' },
          { name: 'clear()', type: '() => void', description: 'Очищает всю очередь уведомлений.' },
        ],
      },
    ],
    usage: [
      'Добавьте toast host (`GrToaster` или аналогичный shell-компонент) один раз в корень приложения.',
      'Используйте returned `id`, если toast должен закрываться вручную после завершения пользовательского действия.',
    ],
    caveats: [
      '`useToast` использует общий reactive store, поэтому изменения видны всем consumers внутри приложения.',
      'Без host-компонента уведомления будут попадать в очередь, но пользователь их не увидит.',
    ],
    integrationNotes: [
      'Подходит для app-shell notifications, optimistic actions и feature-level feedback сообщений.',
      'В showcase-shell уже должен быть mounted toaster host, поэтому demo отражает production-like интеграцию.',
    ],
  },
  useDialogService: {
    overview: [
      '`useDialogService` — императивный сервис диалогов в духе `ElMessageBox` из Element Plus: `confirm`, `prompt` и `alert` вызываются прямо из `<script>`/`.ts`, без вставки компонента в шаблон.',
      'Хост монтируется лениво в `document.body` и наследует app-контекст (i18n, тему, `granular-provider`); обычные вызовы сериализуются FIFO-очередью, `priority` двигает ожидающих, а диалог из `onConfirm` открывается поверх родителя.',
      'Под капотом сервис переиспользует декларативные `GrConfirmDialog`/`GrPromptDialog`, а серверные ошибки в async-`onConfirm` рендерит через `GrResponseErrorBanner`.',
    ],
    examples: createReadyExamples([
      {
        id: 'use-dialog-service-confirm',
        title: 'Imperative confirm (destructive, sm)',
        description: 'Compact destructive confirm с `size: "sm"`, semantic `confirmTone: "danger"` и кастомными `confirmText`/`cancelText`. Возвращает `Promise<boolean>`.',
        previewKey: 'use-dialog-service-confirm',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function removeWorkspace() {',
          "  const ok = await dialog.confirm('This action cannot be undone.', {",
          "    title: 'Delete workspace?',",
          "    size: 'sm',",
          "    confirmText: 'Delete',",
          "    cancelText: 'Keep',",
          "    confirmTone: 'danger',",
          '  })',
          '  if (ok) {',
          '    // ... perform deletion',
          '  }',
          '}',
        ].join('\n'),
        note: '`confirm` резолвится `true` по Confirm и `false` по Cancel/Esc/backdrop — без reject.',
      },
      {
        id: 'use-dialog-service-prompt',
        title: 'Imperative prompt (required, md)',
        description: 'Запрос строки с `label`, `placeholder`, `required` и `size: "md"`. Возвращает `Promise<string | null>` (`null` — отмена).',
        previewKey: 'use-dialog-service-prompt',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function renameProject() {',
          "  const name = await dialog.prompt('Pick a new project name.', {",
          "    title: 'Rename project',",
          "    size: 'md',",
          "    label: 'Project name',",
          "    placeholder: 'e.g. Atlas',",
          '    required: true,',
          "    confirmText: 'Save',",
          '  })',
          '  if (name !== null) {',
          '    // ... persist the new name',
          '  }',
          '}',
        ].join('\n'),
        note: 'Пустое значение блокирует Confirm, пока `required` не удовлетворён; отмена резолвит `null`.',
      },
      {
        id: 'use-dialog-service-alert',
        title: 'Imperative alert (single button, lg)',
        description: 'Информационный диалог с одной кнопкой подтверждения, `size: "lg"` и кастомным `confirmText`. Возвращает `Promise<void>`.',
        previewKey: 'use-dialog-service-alert',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function notifySaved() {',
          "  await dialog.alert('Your workspace settings have been saved.', {",
          "    title: 'Saved',",
          "    size: 'lg',",
          "    confirmText: 'Got it',",
          '  })',
          '  // ... continue after acknowledgement',
          '}',
        ].join('\n'),
        note: '`alert` не показывает кнопку Cancel и резолвится `void` после подтверждения/закрытия.',
      },
      {
        id: 'use-dialog-service-nested',
        title: 'Nested confirm on top',
        description: 'Второе подтверждение спрашивается из `onConfirm` первого. Сервис показывает его **поверх**, а не ставит в очередь: иначе вложенный вызов ждал бы того, кто ждёт его, и внешнее окно зависло бы в загрузке. Нижнее окно на это время помечено `inert`, Esc закрывает верхнее.',
        previewKey: 'use-dialog-service-nested',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          '',
          'async function deleteProject() {',
          "  const deleted = await dialog.confirm('Будут удалены задачи, релизы и вебхуки.', {",
          "    title: 'Удалить проект?',",
          "    confirmText: 'Удалить',",
          "    confirmTone: 'danger',",
          '    async onConfirm() {',
          '      // Открывается поверх первого окна и решает его судьбу.',
          "      return await dialog.confirm('Восстановить будет нечем.', {",
          "        title: 'Точно удалить?',",
          "        size: 'sm',",
          "        confirmText: 'Да, удалить',",
          "        confirmTone: 'danger',",
          '      })',
          '    },',
          '  })',
          '',
          '  if (deleted) {',
          '    // ... удаление подтверждено дважды',
          '  }',
          '}',
        ].join('\n'),
        note: 'Стопка окон здесь не украшение: без неё вложенный вызов встал бы в очередь за тем, кто его ждёт.',
      },
      {
        id: 'use-dialog-service-network',
        title: 'Async onConfirm (network errors + validation)',
        description: 'Imperative `prompt` с async-`onConfirm`, который имитирует сетевой запрос: кнопка Confirm уходит в loading, серверная валидация (HTTP 422) раскладывается на баннер и поле через `ctx.setRawError`, а обрыв сети (`throw`) распознаётся как `kind: "network"`. Диалог остаётся открытым до успешной отправки.',
        previewKey: 'use-dialog-service-network',
        code: [
          "import { useDialogService } from '@feugene/granularity'",
          '',
          'const dialog = useDialogService()',
          'let attempt = 0',
          '',
          'async function inviteTeammate() {',
          "  const email = await dialog.prompt('Send an invite to a teammate.', {",
          "    title: 'Invite teammate',",
          "    label: 'Work email',",
          "    placeholder: 'name@company.com',",
          '    required: true,',
          "    confirmText: 'Send invite',",
          '    // Подключаем Laravel-пресет поверх ядра: fieldErrors лягут на поле `value`.',
          '    errorParsers: presets => [...presets.core, presets.laravel],',
          '    async onConfirm(ctx) {',
          '      attempt += 1',
          '      // Имитируем сетевой запрос — Confirm автоматически переходит в loading.',
          '      await new Promise(resolve => setTimeout(resolve, 700))',
          '',
          '      if (attempt === 1) {',
          '        // Серверная валидация (HTTP 422): баннер + ошибка под полем ввода.',
          '        await ctx.setRawError(',
          "          new Response(JSON.stringify({",
          "            message: 'The given data was invalid.',",
          "            errors: { value: ['This email is already invited.'] },",
          '          }), {',
          '            status: 422,',
          "            headers: { 'Content-Type': 'application/json' },",
          '          }),',
          '        )',
          '        return false',
          '      }',
          '',
          '      if (attempt === 2) {',
          '        // Обрыв сети: throw автоматически прогоняется через парсеры -> kind: "network".',
          "        throw new TypeError('Failed to fetch')",
          '      }',
          '',
          '      // Успех на третьей попытке: диалог закрывается, prompt резолвится значением.',
          '    },',
          '  })',
          '  if (email !== null) {',
          '    // ... persist invitation',
          '  }',
          '}',
        ].join('\n'),
        note: 'Возврат `false` или `throw`/reject оставляет диалог открытым с показанной ошибкой; `setRawError` сам различает валидацию (422 -> warning + поле) и сетевой сбой (network -> danger-баннер).',
      },
    ]),
    apiSections: [
      {
        key: 'returns',
        title: 'Service methods',
        origin: 'manual',
        items: [
          { name: 'confirm(message, options?)', type: 'DialogPromise<boolean>', description: 'Диалог подтверждения; резолвится `true`/`false`.' },
          { name: 'prompt(message, options?)', type: 'DialogPromise<string | null>', description: 'Запрос строки; `null` — отмена/закрытие.' },
          { name: 'alert(message, options?)', type: 'DialogPromise<void>', description: 'Информационный диалог с одной кнопкой.' },
          { name: 'open(kind, message, options?)', type: 'DialogPromise<DialogResult>', description: 'Низкоуровневый вызов с дискриминируемым `{ action, value }`.' },
          { name: 'closeAll()', type: '() => void', description: 'Закрыть все активные и ожидающие в очереди диалоги.' },
          { name: 'setAppContext(ctx)', type: '(ctx: AppContext | null) => void', description: 'Явно задать app-контекст для вызовов вне `setup`.' },
        ],
      },
      {
        key: 'parameters',
        title: 'Common options',
        origin: 'manual',
        items: [
          { name: 'title', type: 'string', description: 'Заголовок диалога.' },
          { name: 'size', type: 'GrDialogSize', description: 'Размер диалога (`sm` / `md` / `lg` / ...).' },
          { name: 'confirmText / cancelText', type: 'string', description: 'Подписи кнопок Confirm и Cancel.' },
          { name: 'confirmTone / confirmVariant', type: 'GrButtonTone / GrButtonVariant', description: 'Семантика и вариант кнопки подтверждения.' },
          { name: 'onConfirm', type: '(ctx) => void | boolean | Promise<...>', description: 'Async-обработчик с loading и обработкой ошибок сервера.' },
          { name: 'errorParsers', type: 'ResponseErrorParser[] | (presets) => ...', description: 'Стратегия парсинга серверных ошибок; по умолчанию universal core.' },
        ],
      },
    ],
    usage: [
      'Используйте для одноразовых сценариев «спросить и забыть» прямо из обработчиков и сторов, без декларативного компонента в шаблоне.',
      'Передавайте `onConfirm` для async-операций: кнопка Confirm переходит в loading, а ошибки сервера показываются прямо в диалоге.',
    ],
    caveats: [
      'Методы работают только в браузере; вызовы вне `setup` требуют предварительного `setAppContext(...)`, иначе i18n/тема могут не наследоваться.',
      'Диалоги сериализуются очередью FIFO: следующий показывается только после закрытия предыдущего.',
    ],
    integrationNotes: [
      'Сервис — тонкий оркестратор поверх `GrConfirmDialog`/`GrPromptDialog`; декларативные компоненты остаются для встроенных в страницу сценариев.',
      'Для серверной валидации используйте `ctx.setRawError(...)` — ошибка раскладывается на баннер `GrResponseErrorBanner` и поля формы.',
    ],
  },
}