export { default } from './DsFileUpload.vue'
export { default as DsFileUpload } from './DsFileUpload.vue'
export { dsFileUploadConfig } from './config'
export { dsFileUploadSafelist } from './safelist'
export * from '../../fileValidation'