export { default } from './DsDrawer.vue'
export { default as DsDrawer } from './DsDrawer.vue'
export { dsDrawerConfig } from './config'
export { dsDrawerSafelist } from './safelist'
export type { DsDrawerProps } from './DsDrawer.vue'
export type { DsDrawerSide, DsDrawerSize } from './dsDrawerStyles'
