export const dsFormFileSafelist = [
  'rounded-[var(--ds-radius-md)]',
  'opacity-60',
  'cursor-not-allowed',
  'absolute',
  'opacity-0',
  'w-px',
  'h-px',
  'pointer-events-none',
  'flex',
  'flex-col',
  'gap-2',
  'flex-wrap',
  'items-center',
  'gap-3',
  'i-lucide-upload',
  'ml-2',
  'i-lucide-x',
  'text-sm',
  'text-[var(--muted-fg)]',
  'truncate',
  'max-w-[240px]',
  'text-xs',
  'hover:text-[var(--fg)]',
  'text-[var(--ds-danger)]',
] as const