import { splitClassTokens } from '../shared/classTokens'
import {
  iconOnlyClass,
  indicatorBaseClass,
  indicatorVariantClassMap,
  itemBaseClass,
  itemDisabledClass,
  itemEnabledClass,
  itemIconClass,
  itemLabelClass,
  itemSelectedClass,
  itemVariantClassMap,
  rootBaseClass,
  rootBlockClass,
  rootVariantClassMap,
} from './dsSegmentedStyles'

export const dsSegmentedClassTokens = {
  rootBaseClass: splitClassTokens(rootBaseClass),
  rootVariantClassMap: Object.values(rootVariantClassMap).flatMap(splitClassTokens),
  rootBlockClass: splitClassTokens(rootBlockClass),
  indicatorBaseClass: splitClassTokens(indicatorBaseClass),
  indicatorVariantClassMap: Object.values(indicatorVariantClassMap).flatMap(splitClassTokens),
  itemBaseClass: splitClassTokens(itemBaseClass),
  itemVariantClassMap: Object.values(itemVariantClassMap).flatMap(splitClassTokens),
  itemSelectedClass: splitClassTokens(itemSelectedClass),
  itemDisabledClass: splitClassTokens(itemDisabledClass),
  itemEnabledClass: splitClassTokens(itemEnabledClass),
  itemLabelClass: splitClassTokens(itemLabelClass),
  itemIconClass: splitClassTokens(itemIconClass),
  iconOnlyClass: splitClassTokens(iconOnlyClass),
  extra: splitClassTokens('opacity-70'),
} as const

export const dsSegmentedSafelist = [...new Set([
  ...dsSegmentedClassTokens.rootBaseClass,
  ...dsSegmentedClassTokens.rootVariantClassMap,
  ...dsSegmentedClassTokens.rootBlockClass,
  ...dsSegmentedClassTokens.indicatorBaseClass,
  ...dsSegmentedClassTokens.indicatorVariantClassMap,
  ...dsSegmentedClassTokens.itemBaseClass,
  ...dsSegmentedClassTokens.itemVariantClassMap,
  ...dsSegmentedClassTokens.itemSelectedClass,
  ...dsSegmentedClassTokens.itemDisabledClass,
  ...dsSegmentedClassTokens.itemEnabledClass,
  ...dsSegmentedClassTokens.itemLabelClass,
  ...dsSegmentedClassTokens.itemIconClass,
  ...dsSegmentedClassTokens.iconOnlyClass,
  ...dsSegmentedClassTokens.extra,
])]
