export { default } from './DsTabs.vue'
export { default as DsTabs } from './DsTabs.vue'
export type { DsTab } from './DsTabs.vue'
export { dsTabsConfig } from './config'
export { dsTabsSafelist } from './safelist'