export const dsBadgeWrapSafelist = [
  'relative',
  'inline-flex',
  'absolute',
  '-top-1',
  '-right-1',
  'h-2',
  'w-2',
  'rounded-full',
  'bg-[var(--ds-danger)]',
  '-top-2',
  '-right-2',
  'min-w-5',
  'h-5',
  'px-1',
  'text-[var(--destructive-fg)]',
  'text-[11px]',
  'font-700',
  'items-center',
  'justify-center',
] as const