export { default } from './GrPromptDialog.vue'
export { default as GrPromptDialog } from './GrPromptDialog.vue'
export type { GrPromptDialogProps } from './GrPromptDialog.vue'
export { grPromptDialogConfig } from './config'
export type { GrPromptDialogEmits } from './GrPromptDialog.vue'
