import { showcaseComponentDetailSections } from '../../app/showcase'

import {
  grButtonExamples,
  grSelectExamples,
  grFileUploadExamples,
  grModalExamples,
  grDialogExamples,
  grDrawerExamples,
  grConfirmDialogExamples,
  grPromptDialogExamples,
  grToasterExamples,
  grLoadingExamples,
  grCollapseExamples,
  grEmptyStateExamples,
  grProgressBarExamples,
  grSkeletonExamples,
  grDropdownExamples,
  grDataTableExamples,
  grPaginationExamples,
  grTabsExamples,
  grTreeExamples,
  grTreeSelectExamples,
  grTooltipExamples,
  grInputExamples,
  grNumberInputExamples,
  grTextareaExamples,
  grSwitchExamples,
  grCheckboxExamples,
  grRadioExamples,
  grRadioGroupExamples,
  grSegmentedExamples,
  grFormFieldExamples,
  grFormFileExamples,
  grFormSectionExamples,
  grInputTagExamples,
  grAlertExamples,
  grAvatarExamples,
  grBadgeExamples,
  grBadgeWrapExamples,
  grCardExamples,
  grBottomNavExamples,
  grNavbarExamples,
  grSidebarExamples,
  grButtonGroupExamples,
  grDropdownMenuExamples,
  grIconExamples,
  grImageViewerExamples,
  grLinkExamples,
  grListExamples,
  grTableExamples,
} from './examples'
import type { ShowcaseComponentDocMeta, ShowcaseComponentExampleDoc } from './types'

function createComponentDocMeta(examples: ShowcaseComponentExampleDoc[]): ShowcaseComponentDocMeta {
  return {
    sections: showcaseComponentDetailSections,
    examples,
  }
}

export const componentDocOverrides: Partial<Record<string, ShowcaseComponentDocMeta>> = {
  GrButton: createComponentDocMeta(grButtonExamples),
  GrSelect: createComponentDocMeta(grSelectExamples),
  GrFileUpload: createComponentDocMeta(grFileUploadExamples),
  GrModal: createComponentDocMeta(grModalExamples),
  GrDialog: createComponentDocMeta(grDialogExamples),
  GrDrawer: createComponentDocMeta(grDrawerExamples),
  GrConfirmDialog: createComponentDocMeta(grConfirmDialogExamples),
  GrPromptDialog: createComponentDocMeta(grPromptDialogExamples),
  GrToaster: createComponentDocMeta(grToasterExamples),
  GrLoading: createComponentDocMeta(grLoadingExamples),
  GrCollapse: createComponentDocMeta(grCollapseExamples),
  GrEmptyState: createComponentDocMeta(grEmptyStateExamples),
  GrProgressBar: createComponentDocMeta(grProgressBarExamples),
  GrSkeleton: createComponentDocMeta(grSkeletonExamples),
  GrDropdown: createComponentDocMeta(grDropdownExamples),
  GrDataTable: createComponentDocMeta(grDataTableExamples),
  GrPagination: createComponentDocMeta(grPaginationExamples),
  GrTabs: createComponentDocMeta(grTabsExamples),
  GrTree: createComponentDocMeta(grTreeExamples),
  GrTreeSelect: createComponentDocMeta(grTreeSelectExamples),
  GrTooltip: createComponentDocMeta(grTooltipExamples),
  GrInput: createComponentDocMeta(grInputExamples),
  GrNumberInput: createComponentDocMeta(grNumberInputExamples),
  GrTextarea: createComponentDocMeta(grTextareaExamples),
  GrSwitch: createComponentDocMeta(grSwitchExamples),
  GrCheckbox: createComponentDocMeta(grCheckboxExamples),
  GrRadio: createComponentDocMeta(grRadioExamples),
  GrRadioGroup: createComponentDocMeta(grRadioGroupExamples),
  GrSegmented: createComponentDocMeta(grSegmentedExamples),
  GrFormField: createComponentDocMeta(grFormFieldExamples),
  GrFormFile: createComponentDocMeta(grFormFileExamples),
  GrFormSection: createComponentDocMeta(grFormSectionExamples),
  GrInputTag: createComponentDocMeta(grInputTagExamples),
  GrAlert: createComponentDocMeta(grAlertExamples),
  GrAvatar: createComponentDocMeta(grAvatarExamples),
  GrBadge: createComponentDocMeta(grBadgeExamples),
  GrBadgeWrap: createComponentDocMeta(grBadgeWrapExamples),
  GrCard: createComponentDocMeta(grCardExamples),
  GrBottomNav: createComponentDocMeta(grBottomNavExamples),
  GrNavbar: createComponentDocMeta(grNavbarExamples),
  GrSidebar: createComponentDocMeta(grSidebarExamples),
  GrButtonGroup: createComponentDocMeta(grButtonGroupExamples),
  GrDropdownMenu: createComponentDocMeta(grDropdownMenuExamples),
  GrIcon: createComponentDocMeta(grIconExamples),
  GrImageViewer: createComponentDocMeta(grImageViewerExamples),
  GrLink: createComponentDocMeta(grLinkExamples),
  GrList: createComponentDocMeta(grListExamples),
  GrTable: createComponentDocMeta(grTableExamples),
}
