import { showcaseComponentDetailSections } from '../../app/showcase'

import {
  dsButtonExamples,
  dsSelectExamples,
  dsFileUploadExamples,
  dsModalExamples,
  dsDialogExamples,
  dsDrawerExamples,
  dsConfirmDialogExamples,
  dsPromptDialogExamples,
  dsToasterExamples,
  dsLoadingExamples,
  dsCollapseExamples,
  dsEmptyStateExamples,
  dsProgressBarExamples,
  dsSkeletonExamples,
  dsDropdownExamples,
  dsDataTableExamples,
  dsPaginationExamples,
  dsTabsExamples,
  dsTreeExamples,
  dsTreeSelectExamples,
  dsTooltipExamples,
  dsInputExamples,
  dsNumberInputExamples,
  dsTextareaExamples,
  dsSwitchExamples,
  dsCheckboxExamples,
  dsRadioExamples,
  dsRadioGroupExamples,
  dsSegmentedExamples,
  dsFormFieldExamples,
  dsFormFileExamples,
  dsFormSectionExamples,
  dsInputTagExamples,
  dsAlertExamples,
  dsAvatarExamples,
  dsBadgeExamples,
  dsBadgeWrapExamples,
  dsCardExamples,
  dsBottomNavExamples,
  dsNavbarExamples,
  dsSidebarExamples,
  dsButtonGroupExamples,
  dsDropdownMenuExamples,
  dsIconExamples,
  dsImageViewerExamples,
  dsLinkExamples,
  dsListExamples,
  dsTableExamples,
} from './examples'
import type { ShowcaseComponentDocMeta, ShowcaseComponentExampleDoc } from './types'

function createComponentDocMeta(examples: ShowcaseComponentExampleDoc[]): ShowcaseComponentDocMeta {
  return {
    sections: showcaseComponentDetailSections,
    examples,
  }
}

export const componentDocOverrides: Partial<Record<string, ShowcaseComponentDocMeta>> = {
  DsButton: createComponentDocMeta(dsButtonExamples),
  DsSelect: createComponentDocMeta(dsSelectExamples),
  DsFileUpload: createComponentDocMeta(dsFileUploadExamples),
  DsModal: createComponentDocMeta(dsModalExamples),
  DsDialog: createComponentDocMeta(dsDialogExamples),
  DsDrawer: createComponentDocMeta(dsDrawerExamples),
  DsConfirmDialog: createComponentDocMeta(dsConfirmDialogExamples),
  DsPromptDialog: createComponentDocMeta(dsPromptDialogExamples),
  DsToaster: createComponentDocMeta(dsToasterExamples),
  DsLoading: createComponentDocMeta(dsLoadingExamples),
  DsCollapse: createComponentDocMeta(dsCollapseExamples),
  DsEmptyState: createComponentDocMeta(dsEmptyStateExamples),
  DsProgressBar: createComponentDocMeta(dsProgressBarExamples),
  DsSkeleton: createComponentDocMeta(dsSkeletonExamples),
  DsDropdown: createComponentDocMeta(dsDropdownExamples),
  DsDataTable: createComponentDocMeta(dsDataTableExamples),
  DsPagination: createComponentDocMeta(dsPaginationExamples),
  DsTabs: createComponentDocMeta(dsTabsExamples),
  DsTree: createComponentDocMeta(dsTreeExamples),
  DsTreeSelect: createComponentDocMeta(dsTreeSelectExamples),
  DsTooltip: createComponentDocMeta(dsTooltipExamples),
  DsInput: createComponentDocMeta(dsInputExamples),
  DsNumberInput: createComponentDocMeta(dsNumberInputExamples),
  DsTextarea: createComponentDocMeta(dsTextareaExamples),
  DsSwitch: createComponentDocMeta(dsSwitchExamples),
  DsCheckbox: createComponentDocMeta(dsCheckboxExamples),
  DsRadio: createComponentDocMeta(dsRadioExamples),
  DsRadioGroup: createComponentDocMeta(dsRadioGroupExamples),
  DsSegmented: createComponentDocMeta(dsSegmentedExamples),
  DsFormField: createComponentDocMeta(dsFormFieldExamples),
  DsFormFile: createComponentDocMeta(dsFormFileExamples),
  DsFormSection: createComponentDocMeta(dsFormSectionExamples),
  DsInputTag: createComponentDocMeta(dsInputTagExamples),
  DsAlert: createComponentDocMeta(dsAlertExamples),
  DsAvatar: createComponentDocMeta(dsAvatarExamples),
  DsBadge: createComponentDocMeta(dsBadgeExamples),
  DsBadgeWrap: createComponentDocMeta(dsBadgeWrapExamples),
  DsCard: createComponentDocMeta(dsCardExamples),
  DsBottomNav: createComponentDocMeta(dsBottomNavExamples),
  DsNavbar: createComponentDocMeta(dsNavbarExamples),
  DsSidebar: createComponentDocMeta(dsSidebarExamples),
  DsButtonGroup: createComponentDocMeta(dsButtonGroupExamples),
  DsDropdownMenu: createComponentDocMeta(dsDropdownMenuExamples),
  DsIcon: createComponentDocMeta(dsIconExamples),
  DsImageViewer: createComponentDocMeta(dsImageViewerExamples),
  DsLink: createComponentDocMeta(dsLinkExamples),
  DsList: createComponentDocMeta(dsListExamples),
  DsTable: createComponentDocMeta(dsTableExamples),
}
