export { default } from './GrModal.vue'
export { default as GrModal } from './GrModal.vue'
export type { GrModalProps } from './GrModal.vue'
export { grModalConfig } from './config'
export type { GrModalScrollBehavior, GrModalSize } from './grModalStyles'
export { grModalSafelist } from './safelist'
