import type { ShowcaseComponentExampleDoc } from '../types'

export const grTreeExamples: ShowcaseComponentExampleDoc[] = [
  {
    id: 'tree-controlled',
    title: 'Controlled selection and reachable drag handle',
    description: 'Выбранный узел живёт снаружи через `v-model:current-key`, поэтому подсветка строки и состояние обёртки не могут разойтись. `dragHandleVisibility` решает, когда видна ручка переноса: по умолчанию `auto` — всегда там, где наведения не бывает.',
    status: 'ready',
    previewKey: 'gr-tree-controlled',
  },
  {
    id: 'tree-expanded-state',
    title: 'Controlled expanded state and branch lines',
    description: 'Показываем `GrTree` как иерархический explorer, где внешняя orchestration управляет раскрытием групп и визуальными branch lines.',
    status: 'ready',
    previewKey: 'gr-tree-expanded-state',
    note: 'Этот сценарий подчёркивает, что `GrTree` хорошо работает как controlled navigation/data primitive, а не только как статичное дерево.',
  },
  {
    id: 'tree-filtering',
    title: 'Filtering through instance API',
    description: 'Фильтрацию важно показывать не как магический prop, а как реальную интеграцию через expose-метод `filter()` и внешний input.',
    status: 'ready',
    previewKey: 'gr-tree-filtering',
    note: 'Полезный integration recipe для search/filter поверх больших справочников и nested navigation.',
  },
  {
    id: 'tree-drag-and-slot',
    title: 'Drag-and-drop with custom row slot',
    description: 'Комбинируем две важные возможности complex-дерева: rearrange drag-and-drop и кастомный рендер строки через default slot.',
    status: 'ready',
    previewKey: 'gr-tree-drag-and-slot',
    note: 'Сценарий особенно важен для real-world деревьев с ownership/status метаданными и операторскими перестановками.',
  },
  {
    id: 'tree-sizes',
    title: 'Шкала размеров',
    description: 'Размер выражен CSS-переменными `--gr-tree-*`: те же точки кастомизации, что и для ручной настройки, — `size` просто задаёт им дефолты.',
    status: 'ready',
    previewKey: 'gr-tree-sizes',
  },
  {
    id: 'tree-checkboxes',
    title: 'Checkboxes and multiple selection',
    description: 'Чекбоксы включаются пропом `show-checkbox`, набор ведётся через `v-model:checked-keys`. Родитель отмечается каскадом и показывает `mixed`, когда отмечена часть детей; `check-strictly` эту связь отключает. Состояние объявляется на самом узле (`aria-checked`), а квадратик остаётся декоративным — вкладывать интерактивный чекбокс внутрь роли `treeitem` нельзя.',
    status: 'ready',
    previewKey: 'gr-tree-checkboxes',
  },
  {
    id: 'tree-lazy',
    title: 'Lazy branches',
    description: 'В режиме `lazy` дети ветки приходят по её раскрытию: `load` получает узел и `resolve`, на время запроса строка показывает спиннер и помечается `aria-busy`. Повторное раскрытие запрос не делает. Лист объявляется полем `isLeaf` в данных — иначе дерево считает ветку разворачиваемой, пока не доказано обратное.',
    status: 'ready',
    previewKey: 'gr-tree-lazy',
  },
  {
    id: 'tree-keyboard',
    title: 'Клавиатура и режимы раскрытия',
    description: 'Typeahead по первым буквам, `*` на весь уровень, плюс `accordion` и `expandOnClickNode` — то, чем дерево управляется без мыши.',
    status: 'ready',
    previewKey: 'gr-tree-keyboard',
  },
  {
    id: 'tree-virtual',
    title: 'Дерево на 10 000 узлов',
    description: 'С `virtual` и `maxHeight` дерево держит в DOM только окно вокруг вьюпорта, а скроллером становится его корень. Плоская разметка строк это и открывает.',
    status: 'ready',
    previewKey: 'gr-tree-virtual',
    note: '`aria-setsize`/`aria-posinset` остаются от полного набора, а не от окна. Перетаскивание при этом работает по отрисованным строкам: уронить узел на тот, которого нет на экране, нельзя.',
  },
  {
    id: 'tree-explorer',
    title: 'Вид «Проводник»: плотность и колена связей',
    description: 'Максимум узлов на экран и полные колена: горизонтальная черта соединяет узел с родителем, а вертикаль обрывается на середине последнего ребёнка — по шести уровням видно, какие ветки ещё продолжаются. Вид задаётся набором `grTreeViewVars.explorer`, а не пропом: он раскладывается в `style` и композируется с `size`.',
    status: 'ready',
    previewKey: 'gr-tree-explorer',
  },
  {
    id: 'tree-rail',
    title: 'Вид «Рельс»: навигация по разделам',
    description: 'Уровень несёт рельс, а выбранная строка — сплошная плашка, обрезанная слева по отступу. Текст на ней перекрашен токеном `--gr-tree-row-current-color`: без него он остался бы цветом обычной строки и на насыщенной подложке стал бы нечитаемым.',
    status: 'ready',
    previewKey: 'gr-tree-rail',
  },
  {
    id: 'tree-outline',
    title: 'Вид «Оглавление»: иерархию несёт набор',
    description: 'Ни направляющих, ни подложек — уровень читается кеглем и цветом, как в оглавлении книги. Ступени по уровням задаются `rowClass`: это единственное, чего набор значений сделать не может, потому что уровень строки знает только разметка.',
    status: 'ready',
    previewKey: 'gr-tree-outline',
  },
]
